version: '3.6'
x-build:
  &build
  context: .
  dockerfile: .deploy/Dockerfile
x-env:
  &env
  WS_LOGGING_LEVEL: ${LOGGING_LEVEL:-DEBUG}
  WS_REST_SERVER_PORT: ${WS_REST_SERVER_PORT:-8080}
  WS_WEBSOCKET_SERVER_PORT: ${WS_WS_SERVER_PORT:-7778}
  WS_JWT_SECRET_KEY: ${WS_JWT_SECRET_KEY:-asd}
services:
  web:
    image: ws_notification/ws_notification:${VERSION:-latest}
    build: *build
    environment: *env
    restart: always
    ports:
      - '8080:8080'
      - '7778:7778'
    volumes:
      - ws_notification:/usr/src/app/
    networks:
      - backend


networks:
  backend:
    driver: bridge

volumes:
  ws_notification:

