version: '3.6'
x-build:
  &build
  context: .deploy/
x-env:
  &env
  WS_LOGGING_LEVEL: ${LOGGING_LEVEL:-DEBUG}
  WS_REST_SERVER_PORT: ${WS_REST_SERVER_PORT:-8090}
  WS_WEBSOCKET_SERVER_PORT: ${WS_WS_SERVER_PORT:-7777}
  WS_DB_USER
services:
  web:
    image: ws_notification/ws_notification:${VERSION:-latest}
    build: *build
    environment: *env
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    volumes:
      - api:/usr/src/app/
    networks:
      - backend


networks:
  backend:
    driver: bridge

volumes:
  api:

