basePath: /
definitions:
  auth.JWTAuth:
    properties:
      jwt_token:
        type: string
    type: object
  ws.Message:
    properties:
      msg:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: baybaraandrey@gmail.com
    name: Andrey Baybara
  description: This is a ws notifications app
  license: {}
  title: Swagger Cyberjin notifications API
  version: 0.0.1
paths:
  /_api/:
    get:
      description: Application monitor
      produces:
      - text/plain
      responses:
        "200": {}
      summary: Application monitor
      tags:
      - app-monitor
  /api/v1/notifications/:
    post:
      description: notify client
      summary: notify client
      tags:
      - rest-notifications
  /ws/v1/notifications/:
    get:
      consumes:
      - application/json
      description: notifications api jwt token must be sended after websocet connection
        established
      parameters:
      - description: jwt token
        in: body
        name: query
        required: true
        schema:
          $ref: '#/definitions/auth.JWTAuth'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ws.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ws.Message'
      summary: notifications api
      tags:
      - ws-notifications
swagger: "2.0"
